releaseTargetBranch: master
commentOnReleasablePR: true
labelsToIgnore: ["pr-release: don't release"]
releaseName: "{version}"
releaseLabel: "pr-release: release {version} :shipit:"
noReleaseLabel: "pr-release: won't release"
