name: release_bot

on:
  push:

jobs:
  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Release-Bot
      run: pip install release-bot
      
    - name: Run Release Bot
      run: |
        release-bot -c https://github.com/justinkumpe/workflowTest/.github/workflows/config.yml
